// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 694ba3e94fb76b4c "test", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' | 'Variant 3' // Variant
}} Props

 */
import { routes } from "./chunks/chunk-VAWW4KIH.js";

// virtual:desktop-component
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/desktop-component-iqEx.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback as useActiveVariantCallback2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useOnVariantChange as useOnVariantChange2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/LPmkagtApkl3AUVroZOY/sDUO5ZY6jGQiVCJBpo3R/gb4SAU21p.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFX = withFX(motion.div);
var cycleOrder = ["QC7nUFQy_", "RQnWSzAa2"];
var serializationHash = "framer-zAtlt";
var variantClassNames = {
	QC7nUFQy_: "framer-v-1uyk5dt",
	RQnWSzAa2: "framer-v-hikaev",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 4,
	type: "spring",
};
var transition2 = {
	delay: 0,
	duration: 4,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 51,
	y: 0,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "QC7nUFQy_",
	"Variant 2": "RQnWSzAa2",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "QC7nUFQy_",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "QC7nUFQy_",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppearn922d6 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("RQnWSzAa2", true), 4e3);
	});
	useOnVariantChange(baseVariant, {
		default: onAppearn922d6,
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1uyk5dt",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"QC7nUFQy_"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								RQnWSzAa2: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-jnzzxt"}
							data-border={true}
							data-framer-name={"Rectangle 1625"}
							layoutDependency={layoutDependency}
							layoutId={"I722:21065;717:20483"}
							style={{
								"--border-bottom-width": "2px",
								"--border-color": "rgb(8, 28, 70)",
								"--border-left-width": "2px",
								"--border-right-width": "2px",
								"--border-style": "solid",
								"--border-top-width": "2px",
								borderBottomLeftRadius: 12.5,
								borderBottomRightRadius: 12.5,
								borderTopLeftRadius: 12.5,
								borderTopRightRadius: 12.5,
							}}
						/>
						<MotionDivWithFX
							__framer__loop={animation}
							__framer__loopEffectEnabled={true}
							__framer__loopPauseOffscreen={true}
							__framer__loopRepeatDelay={0}
							__framer__loopRepeatType={"loop"}
							__framer__loopTransition={transition2}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							className={"framer-7meel4"}
							data-framer-name={"Rectangle 1626"}
							layoutDependency={layoutDependency}
							layoutId={"I722:21065;717:20484"}
							style={{
								backgroundColor: "rgb(8, 28, 70)",
								borderBottomLeftRadius: 12.5,
								borderBottomRightRadius: 12.5,
								borderTopLeftRadius: 12.5,
								borderTopRightRadius: 12.5,
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-zAtlt.framer-1tgtaqi, .framer-zAtlt .framer-1tgtaqi { display: block; }",
	".framer-zAtlt.framer-1uyk5dt { gap: 0px; height: 15px; overflow: visible; position: relative; width: 66px; }",
	".framer-zAtlt .framer-jnzzxt { flex: none; height: 15px; left: 0px; position: absolute; top: 0px; width: 66px; }",
	".framer-zAtlt .framer-7meel4 { flex: none; height: 15px; left: 0px; position: absolute; top: 0px; width: 15px; }",
	'.framer-zAtlt[data-border="true"]::after, .framer-zAtlt [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var Framergb4SAU21p = withCSS(Component, css, "framer-zAtlt");
var stdin_default = Framergb4SAU21p;
Framergb4SAU21p.displayName = "loader";
Framergb4SAU21p.defaultProps = {
	height: 15,
	width: 66,
};
addPropertyControls(Framergb4SAU21p, {
	variant: {
		options: ["QC7nUFQy_", "RQnWSzAa2"],
		optionTitles: ["Variant 1", "Variant 2"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	Framergb4SAU21p,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framer.com/m/desktop-component-iqEx.js
var LoaderFonts = getFonts(stdin_default);
var cycleOrder2 = ["l9UZ5xyJt", "Xhfv0P_Uf", "Oy1CEl_9C"];
var serializationHash2 = "framer-KD6PO";
var variantClassNames2 = {
	l9UZ5xyJt: "framer-v-192b1nv",
	Oy1CEl_9C: "framer-v-irnyhu",
	Xhfv0P_Uf: "framer-v-1x8vhso",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	"Variant 1": "l9UZ5xyJt",
	"Variant 2": "Xhfv0P_Uf",
	"Variant 3": "Oy1CEl_9C",
};
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "l9UZ5xyJt",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const { style, className, layoutId, variant, ...restProps } =
		getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "l9UZ5xyJt",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback2(baseVariant);
	const onAppear16tkpue = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("Xhfv0P_Uf", true), 4e3);
	});
	const onAppearxg158y = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("Oy1CEl_9C", true), 4e3);
	});
	const onAppearj2862w = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("l9UZ5xyJt", true), 4e3);
	});
	const onTap15afhja = activeVariantCallback(async (...args) => {
		setVariant("l9UZ5xyJt");
	});
	const onTapnf29lg = activeVariantCallback(async (...args) => {
		setVariant("Xhfv0P_Uf");
	});
	const onTap1ilhfep = activeVariantCallback(async (...args) => {
		setVariant("Oy1CEl_9C");
	});
	useOnVariantChange2(baseVariant, {
		default: onAppear16tkpue,
		Oy1CEl_9C: onAppearj2862w,
		Xhfv0P_Uf: onAppearxg158y,
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-192b1nv",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"l9UZ5xyJt"}
						ref={refBinding}
						style={{
							backgroundColor: "rgb(232, 232, 232)",
							...style,
						}}
						{...addPropertyOverrides2(
							{
								Oy1CEl_9C: {
									"data-framer-name": "Variant 3",
								},
								Xhfv0P_Uf: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-f7epi1"}
							data-framer-name={"Frame 2608592"}
							layoutDependency={layoutDependency}
							layoutId={"YMEjAYNSz"}
						>
							<motion2.div
								className={"framer-859o9q"}
								data-framer-name={"Frame 2608598"}
								layoutDependency={layoutDependency}
								layoutId={"BUciK6C3n"}
							>
								<motion2.div
									className={"framer-1mhiz1s"}
									data-framer-name={"Frame 2608599"}
									layoutDependency={layoutDependency}
									layoutId={"Cinh4PrS8"}
								>
									<motion2.div
										className={"framer-inne47"}
										data-framer-name={"Frame 2608598"}
										layoutDependency={layoutDependency}
										layoutId={"y10VpalVK"}
									>
										<motion2.div
											className={"framer-1tsoghh"}
											layoutDependency={layoutDependency}
											layoutId={"J_Ja7wcT0"}
										>
											<Image
												background={{
													alt: "",
													fit: "fit",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															(48 +
																((componentViewport?.height || 800) -
																	96 -
																	((componentViewport?.height || 800) - 96) *
																		1) /
																	2) +
															(0 +
																(((componentViewport?.height || 800) - 96) * 1 -
																	0 -
																	(((componentViewport?.height || 800) - 96) *
																		1 -
																		0) *
																		1) /
																	2) +
															0 +
															0 +
															(0 +
																(Math.max(
																	0,
																	((((componentViewport?.height || 800) - 96) *
																		1 -
																		0) *
																		1 -
																		0 -
																		0) /
																		1,
																) *
																	1 -
																	0 -
																	(Math.max(
																		0,
																		((((componentViewport?.height || 800) -
																			96) *
																			1 -
																			0) *
																			1 -
																			0 -
																			0) /
																			1,
																	) *
																		1 -
																		0) *
																		1) /
																	2) +
															0 +
															0 +
															0,
													),
													pixelHeight: 3e3,
													pixelWidth: 1801,
													positionX: "center",
													positionY: "center",
													sizes: "451px",
													src: "https://framerusercontent.com/images/uycbSgfOj9XTUUwiXtRdkrIFizE.png?width=1801&height=3000",
													srcSet:
														"https://framerusercontent.com/images/uycbSgfOj9XTUUwiXtRdkrIFizE.png?scale-down-to=1024&width=1801&height=3000 614w,https://framerusercontent.com/images/uycbSgfOj9XTUUwiXtRdkrIFizE.png?scale-down-to=2048&width=1801&height=3000 1229w,https://framerusercontent.com/images/uycbSgfOj9XTUUwiXtRdkrIFizE.png?width=1801&height=3000 1801w",
												}}
												className={"framer-jfmmrh"}
												data-framer-name={"Mask group"}
												layoutDependency={layoutDependency}
												layoutId={"s43Qv3tF9"}
												style={{
													opacity: 1,
												}}
												variants={{
													Oy1CEl_9C: {
														opacity: 0,
													},
													Xhfv0P_Uf: {
														opacity: 0,
													},
												}}
											/>
											<Image
												background={{
													alt: "",
													fit: "fit",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															(48 +
																((componentViewport?.height || 800) -
																	96 -
																	((componentViewport?.height || 800) - 96) *
																		1) /
																	2) +
															(0 +
																(((componentViewport?.height || 800) - 96) * 1 -
																	0 -
																	(((componentViewport?.height || 800) - 96) *
																		1 -
																		0) *
																		1) /
																	2) +
															0 +
															0 +
															(0 +
																(Math.max(
																	0,
																	((((componentViewport?.height || 800) - 96) *
																		1 -
																		0) *
																		1 -
																		0 -
																		0) /
																		1,
																) *
																	1 -
																	0 -
																	(Math.max(
																		0,
																		((((componentViewport?.height || 800) -
																			96) *
																			1 -
																			0) *
																			1 -
																			0 -
																			0) /
																			1,
																	) *
																		1 -
																		0) *
																		1) /
																	2) +
															0 +
															0 +
															0,
													),
													pixelHeight: 3e3,
													pixelWidth: 1801,
													positionX: "center",
													positionY: "center",
													sizes: "451px",
													src: "https://framerusercontent.com/images/GeaoscbEftguzqlOcpJ19aTH8.png?width=1801&height=3000",
													srcSet:
														"https://framerusercontent.com/images/GeaoscbEftguzqlOcpJ19aTH8.png?scale-down-to=1024&width=1801&height=3000 614w,https://framerusercontent.com/images/GeaoscbEftguzqlOcpJ19aTH8.png?scale-down-to=2048&width=1801&height=3000 1229w,https://framerusercontent.com/images/GeaoscbEftguzqlOcpJ19aTH8.png?width=1801&height=3000 1801w",
												}}
												className={"framer-14fw8rm"}
												data-framer-name={"Mask group"}
												layoutDependency={layoutDependency}
												layoutId={"kuNAEZ1FE"}
												style={{
													opacity: 0,
												}}
												variants={{
													Xhfv0P_Uf: {
														opacity: 1,
													},
												}}
											/>
											<Image
												background={{
													alt: "",
													fit: "fit",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															(48 +
																((componentViewport?.height || 800) -
																	96 -
																	((componentViewport?.height || 800) - 96) *
																		1) /
																	2) +
															(0 +
																(((componentViewport?.height || 800) - 96) * 1 -
																	0 -
																	(((componentViewport?.height || 800) - 96) *
																		1 -
																		0) *
																		1) /
																	2) +
															0 +
															0 +
															(0 +
																(Math.max(
																	0,
																	((((componentViewport?.height || 800) - 96) *
																		1 -
																		0) *
																		1 -
																		0 -
																		0) /
																		1,
																) *
																	1 -
																	0 -
																	(Math.max(
																		0,
																		((((componentViewport?.height || 800) -
																			96) *
																			1 -
																			0) *
																			1 -
																			0 -
																			0) /
																			1,
																	) *
																		1 -
																		0) *
																		1) /
																	2) +
															0 +
															0 +
															0,
													),
													pixelHeight: 3e3,
													pixelWidth: 1801,
													positionX: "center",
													positionY: "center",
													sizes: "451px",
													src: "https://framerusercontent.com/images/D4nB28Dy3ciUbiLTvNmO5fdwHw.png?width=1801&height=3000",
													srcSet:
														"https://framerusercontent.com/images/D4nB28Dy3ciUbiLTvNmO5fdwHw.png?scale-down-to=1024&width=1801&height=3000 614w,https://framerusercontent.com/images/D4nB28Dy3ciUbiLTvNmO5fdwHw.png?scale-down-to=2048&width=1801&height=3000 1229w,https://framerusercontent.com/images/D4nB28Dy3ciUbiLTvNmO5fdwHw.png?width=1801&height=3000 1801w",
												}}
												className={"framer-1hm0afd"}
												data-framer-name={"Mask group"}
												fitImageDimension={"height"}
												layoutDependency={layoutDependency}
												layoutId={"iMLtLNRBd"}
												style={{
													opacity: 0,
												}}
												variants={{
													Oy1CEl_9C: {
														opacity: 1,
													},
												}}
											/>
										</motion2.div>
										<motion2.div
											className={"framer-15v8qpq"}
											data-framer-name={"Frame 2608595"}
											layoutDependency={layoutDependency}
											layoutId={"n9wR5Qi1b"}
										>
											<motion2.div
												className={"framer-v7rmry"}
												data-border={true}
												data-framer-name={"Desktop / Main Button 2"}
												data-highlight={true}
												layoutDependency={layoutDependency}
												layoutId={"gfDg1XeIP"}
												onTap={onTap15afhja}
												style={{
													"--border-bottom-width": "2px",
													"--border-color": "rgb(8, 28, 70)",
													"--border-left-width": "2px",
													"--border-right-width": "2px",
													"--border-style": "solid",
													"--border-top-width": "2px",
													backgroundColor: "rgb(8, 28, 70)",
													borderBottomLeftRadius: 100,
													borderBottomRightRadius: 100,
													borderTopLeftRadius: 100,
													borderTopRightRadius: 100,
												}}
												variants={{
													Oy1CEl_9C: {
														backgroundColor: "rgba(8, 28, 70, 0.1)",
													},
													Xhfv0P_Uf: {
														backgroundColor: "rgba(8, 28, 70, 0.1)",
													},
												}}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-117oakt"}
													data-framer-name={"Topic 1"}
													fonts={["GF;Plus Jakarta Sans-700"]}
													layoutDependency={layoutDependency}
													layoutId={"kXNei4O13"}
													style={{
														"--extracted-r6o4lv": "rgb(255, 255, 255)",
														"--framer-paragraph-spacing": "0px",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React2.Fragment>
														<motion2.p
															style={{
																"--font-selector":
																	"R0Y7UGx1cyBKYWthcnRhIFNhbnMtNzAw",
																"--framer-font-family":
																	'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
																"--framer-font-size": "20px",
																"--framer-font-weight": "700",
																"--framer-line-height": "25px",
																"--framer-text-alignment": "center",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, rgb(255, 255, 255))",
															}}
														>
															{"Topic 1"}
														</motion2.p>
													</React2.Fragment>
												</RichText>
											</motion2.div>
											<motion2.div
												className={"framer-1tww205"}
												data-border={true}
												data-framer-name={"Desktop / Main Button 3"}
												data-highlight={true}
												layoutDependency={layoutDependency}
												layoutId={"BOXwuOMIE"}
												onTap={onTapnf29lg}
												style={{
													"--border-bottom-width": "2px",
													"--border-color": "rgb(8, 28, 70)",
													"--border-left-width": "2px",
													"--border-right-width": "2px",
													"--border-style": "solid",
													"--border-top-width": "2px",
													backgroundColor: "rgba(8, 28, 70, 0.1)",
													borderBottomLeftRadius: 100,
													borderBottomRightRadius: 100,
													borderTopLeftRadius: 100,
													borderTopRightRadius: 100,
												}}
												variants={{
													Xhfv0P_Uf: {
														backgroundColor: "rgb(8, 28, 70)",
													},
												}}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-1ful7dt"}
													data-framer-name={"Topic 2"}
													fonts={["GF;Plus Jakarta Sans-700"]}
													layoutDependency={layoutDependency}
													layoutId={"fNLDcFRNL"}
													style={{
														"--extracted-r6o4lv": "rgb(255, 255, 255)",
														"--framer-paragraph-spacing": "0px",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React2.Fragment>
														<motion2.p
															style={{
																"--font-selector":
																	"R0Y7UGx1cyBKYWthcnRhIFNhbnMtNzAw",
																"--framer-font-family":
																	'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
																"--framer-font-size": "20px",
																"--framer-font-weight": "700",
																"--framer-line-height": "25px",
																"--framer-text-alignment": "center",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, rgb(255, 255, 255))",
															}}
														>
															{"Topic 2"}
														</motion2.p>
													</React2.Fragment>
												</RichText>
											</motion2.div>
											<motion2.div
												className={"framer-vq0kjb"}
												data-border={true}
												data-framer-name={"Desktop / Main Button 4"}
												data-highlight={true}
												layoutDependency={layoutDependency}
												layoutId={"KNaAE5Lmy"}
												onTap={onTap1ilhfep}
												style={{
													"--border-bottom-width": "2px",
													"--border-color": "rgb(8, 28, 70)",
													"--border-left-width": "2px",
													"--border-right-width": "2px",
													"--border-style": "solid",
													"--border-top-width": "2px",
													backgroundColor: "rgba(8, 28, 70, 0.1)",
													borderBottomLeftRadius: 100,
													borderBottomRightRadius: 100,
													borderTopLeftRadius: 100,
													borderTopRightRadius: 100,
												}}
												variants={{
													Oy1CEl_9C: {
														backgroundColor: "rgb(8, 28, 70)",
													},
												}}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-13ti3p"}
													data-framer-name={"Topic 3"}
													fonts={["GF;Plus Jakarta Sans-700"]}
													layoutDependency={layoutDependency}
													layoutId={"OubetqN21"}
													style={{
														"--extracted-r6o4lv": "rgb(255, 255, 255)",
														"--framer-paragraph-spacing": "0px",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React2.Fragment>
														<motion2.p
															style={{
																"--font-selector":
																	"R0Y7UGx1cyBKYWthcnRhIFNhbnMtNzAw",
																"--framer-font-family":
																	'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
																"--framer-font-size": "20px",
																"--framer-font-weight": "700",
																"--framer-line-height": "25px",
																"--framer-text-alignment": "center",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, rgb(255, 255, 255))",
															}}
														>
															{"Topic 3"}
														</motion2.p>
													</React2.Fragment>
												</RichText>
											</motion2.div>
										</motion2.div>
										<ComponentViewportProvider
											height={15}
											width={"66px"}
											y={
												(componentViewport?.y || 0) +
												(48 +
													((componentViewport?.height || 800) -
														96 -
														((componentViewport?.height || 800) - 96) * 1) /
														2) +
												(0 +
													(((componentViewport?.height || 800) - 96) * 1 -
														0 -
														(((componentViewport?.height || 800) - 96) * 1 -
															0) *
															1) /
														2) +
												0 +
												0 +
												(0 +
													(Math.max(
														0,
														((((componentViewport?.height || 800) - 96) * 1 -
															0) *
															1 -
															0 -
															0) /
															1,
													) *
														1 -
														0 -
														(Math.max(
															0,
															((((componentViewport?.height || 800) - 96) * 1 -
																0) *
																1 -
																0 -
																0) /
																1,
														) *
															1 -
															0) *
															1) /
														2) +
												0 +
												(0 +
													(Math.max(
														0,
														((Math.max(
															0,
															((((componentViewport?.height || 800) - 96) * 1 -
																0) *
																1 -
																0 -
																0) /
																1,
														) *
															1 -
															0) *
															1 -
															0 -
															96) /
															1,
													) *
														1 +
														49) +
													32)
											}
										>
											<SmartComponentScopedContainer
												className={"framer-3mkl4x-container"}
												layoutDependency={layoutDependency}
												layoutId={"CfAYepeqv-container"}
												nodeId={"CfAYepeqv"}
												rendersWithMotion={true}
												scopeId={"eV8ELUnGI"}
											>
												{_jsx2(stdin_default, {
													height: "100%",
													id: "CfAYepeqv",
													layoutId: "CfAYepeqv",
													style: {
														height: "100%",
														width: "100%",
													},
													variant: "QC7nUFQy_",
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									</motion2.div>
								</motion2.div>
							</motion2.div>
						</motion2.div>
						<motion2.div
							className={"framer-p3g15a"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"l6D_Df9w_"}
						>
							<motion2.div
								className={"framer-uh5634"}
								data-framer-name={"Text section 1"}
								layoutDependency={layoutDependency}
								layoutId={"HCXWn9ER6"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-m9qwcx"}
									data-framer-name={"Header"}
									fonts={["GF;Plus Jakarta Sans-800"]}
									layoutDependency={layoutDependency}
									layoutId={"Fn408MVAz"}
									style={{
										"--extracted-r6o4lv": "rgb(8, 28, 70)",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides2(
										{
											Oy1CEl_9C: {
												children: (
													<React2.Fragment>
														<motion2.p
															style={{
																"--font-selector":
																	"R0Y7UGx1cyBKYWthcnRhIFNhbnMtODAw",
																"--framer-font-family":
																	'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
																"--framer-font-size": "60px",
																"--framer-font-weight": "800",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, rgb(8, 28, 70))",
															}}
														>
															{"Header 3"}
														</motion2.p>
													</React2.Fragment>
												),
											},
											Xhfv0P_Uf: {
												children: (
													<React2.Fragment>
														<motion2.p
															style={{
																"--font-selector":
																	"R0Y7UGx1cyBKYWthcnRhIFNhbnMtODAw",
																"--framer-font-family":
																	'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
																"--framer-font-size": "60px",
																"--framer-font-weight": "800",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, rgb(8, 28, 70))",
															}}
														>
															{"Header 2"}
														</motion2.p>
													</React2.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React2.Fragment>
										<motion2.p
											style={{
												"--font-selector": "R0Y7UGx1cyBKYWthcnRhIFNhbnMtODAw",
												"--framer-font-family":
													'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
												"--framer-font-size": "60px",
												"--framer-font-weight": "800",
												"--framer-text-color":
													"var(--extracted-r6o4lv, rgb(8, 28, 70))",
											}}
										>
											{"Header 1"}
										</motion2.p>
									</React2.Fragment>
								</RichText>
								<motion2.div
									className={"framer-oak47s"}
									data-framer-name={"Content"}
									layoutDependency={layoutDependency}
									layoutId={"EGtcET5ko"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-12ojwdu"}
										data-framer-name={"Paragraph"}
										fonts={[
											"GF;Plus Jakarta Sans-regular",
											"GF;Plus Jakarta Sans-700",
										]}
										layoutDependency={layoutDependency}
										layoutId={"xJlVvLoZr"}
										style={{
											"--extracted-14qxiz": "rgb(34, 34, 34)",
											"--extracted-1iakedh": "rgb(34, 34, 34)",
											"--extracted-1o3d6wc": "rgb(12, 80, 239)",
											"--extracted-2gxw0f": "rgb(34, 34, 34)",
											"--extracted-e385wm": "rgb(12, 80, 239)",
											"--extracted-hl0iuy": "rgb(12, 80, 239)",
											"--extracted-o257m": "rgb(12, 80, 239)",
											"--extracted-r6o4lv": "rgb(34, 34, 34)",
											"--extracted-zp3slp": "rgb(12, 80, 239)",
											"--framer-paragraph-spacing": "0px",
										}}
										variants={{
											Oy1CEl_9C: {
												"--extracted-16eqno4": "rgb(12, 80, 239)",
											},
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides2(
											{
												Oy1CEl_9C: {
													children: (
														<React2.Fragment>
															<motion2.p
																style={{
																	"--font-selector":
																		"R0Y7UGx1cyBKYWthcnRhIFNhbnMtcmVndWxhcg==",
																	"--framer-font-family":
																		'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
																	"--framer-line-height": "22px",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, rgb(34, 34, 34))",
																}}
															>
																{"Whether you need to send a parcel to "}
																<Link
																	href={
																		"https://parcel2go.com/parcel-delivery/australia"
																	}
																	motionChild={true}
																	nodeId={"xJlVvLoZr"}
																	openInNewTab={false}
																	relValues={[]}
																	scopeId={"eV8ELUnGI"}
																	smoothScroll={false}
																>
																	<motion2.a>
																		<motion2.span
																			style={{
																				"--font-selector":
																					"R0Y7UGx1cyBKYWthcnRhIFNhbnMtNzAw",
																				"--framer-font-weight": "700",
																				"--framer-text-color":
																					"var(--extracted-hl0iuy, rgb(12, 80, 239))",
																				"--framer-text-decoration": "underline",
																			}}
																		>
																			{"Australia"}
																		</motion2.span>
																	</motion2.a>
																</Link>
																{", the "}
																<Link
																	href={
																		"https://parcel2go.com/parcel-delivery/usa"
																	}
																	motionChild={true}
																	nodeId={"xJlVvLoZr"}
																	openInNewTab={false}
																	relValues={[]}
																	scopeId={"eV8ELUnGI"}
																	smoothScroll={false}
																>
																	<motion2.a>
																		<motion2.span
																			style={{
																				"--font-selector":
																					"R0Y7UGx1cyBKYWthcnRhIFNhbnMtNzAw",
																				"--framer-font-weight": "700",
																				"--framer-text-color":
																					"var(--extracted-zp3slp, rgb(12, 80, 239))",
																				"--framer-text-decoration": "underline",
																			}}
																		>
																			{"USA"}
																		</motion2.span>
																	</motion2.a>
																</Link>
																{
																	" or beyond, we will send you all the documents you need to clear customs."
																}
															</motion2.p>
															<motion2.p
																style={{
																	"--font-selector":
																		"R0Y7UGx1cyBKYWthcnRhIFNhbnMtcmVndWxhcg==",
																	"--framer-font-family":
																		'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
																	"--framer-line-height": "22px",
																	"--framer-text-color":
																		"var(--extracted-2gxw0f, rgb(34, 34, 34))",
																}}
															>
																{"Our "}
																<Link
																	href={
																		"https://parcel2go.com/international-shipping-hub"
																	}
																	motionChild={true}
																	nodeId={"xJlVvLoZr"}
																	openInNewTab={false}
																	relValues={[]}
																	scopeId={"eV8ELUnGI"}
																	smoothScroll={false}
																>
																	<motion2.a>
																		<motion2.span
																			style={{
																				"--font-selector":
																					"R0Y7UGx1cyBKYWthcnRhIFNhbnMtNzAw",
																				"--framer-font-weight": "700",
																				"--framer-text-color":
																					"var(--extracted-16eqno4, rgb(12, 80, 239))",
																				"--framer-text-decoration": "underline",
																			}}
																		>
																			{"International Shipping Hub"}
																		</motion2.span>
																	</motion2.a>
																</Link>
																{
																	" is full of helpful information for sending a parcel to the EU, with details on EU VAT, shipping restrictions and more."
																}
															</motion2.p>
														</React2.Fragment>
													),
												},
												Xhfv0P_Uf: {
													children: (
														<React2.Fragment>
															<motion2.p
																style={{
																	"--font-selector":
																		"R0Y7UGx1cyBKYWthcnRhIFNhbnMtcmVndWxhcg==",
																	"--framer-font-family":
																		'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
																	"--framer-line-height": "22px",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, rgb(34, 34, 34))",
																}}
															>
																{
																	"Booking your parcel delivery is easy, no matter where in the world you\u2019re shipping to! All you need to do is put your parcel\u2019s destination and measurements into our "
																}
																<Link
																	href={"https://parcel2go.com/quick-quote"}
																	motionChild={true}
																	nodeId={"xJlVvLoZr"}
																	openInNewTab={false}
																	relValues={[]}
																	scopeId={"eV8ELUnGI"}
																	smoothScroll={false}
																>
																	<motion2.a>
																		<motion2.span
																			style={{
																				"--font-selector":
																					"R0Y7UGx1cyBKYWthcnRhIFNhbnMtNzAw",
																				"--framer-font-weight": "700",
																				"--framer-text-color":
																					"var(--extracted-hl0iuy, rgb(12, 80, 239))",
																				"--framer-text-decoration": "underline",
																			}}
																		>
																			{"quick quote tool"}
																		</motion2.span>
																	</motion2.a>
																</Link>
																{
																	". From there you can compare parcel prices from the most reliable "
																}
																<Link
																	href={
																		"https://parcel2go.com/international-couriers"
																	}
																	motionChild={true}
																	nodeId={"xJlVvLoZr"}
																	openInNewTab={false}
																	relValues={[]}
																	scopeId={"eV8ELUnGI"}
																	smoothScroll={false}
																>
																	<motion2.a>
																		<motion2.span
																			style={{
																				"--font-selector":
																					"R0Y7UGx1cyBKYWthcnRhIFNhbnMtNzAw",
																				"--framer-font-weight": "700",
																				"--framer-text-color":
																					"var(--extracted-zp3slp, rgb(12, 80, 239))",
																				"--framer-text-decoration": "underline",
																			}}
																		>
																			{"international couriers"}
																		</motion2.span>
																	</motion2.a>
																</Link>
																{"."}
															</motion2.p>
														</React2.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React2.Fragment>
											<motion2.p
												style={{
													"--font-selector":
														"R0Y7UGx1cyBKYWthcnRhIFNhbnMtcmVndWxhcg==",
													"--framer-font-family":
														'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
													"--framer-line-height": "22px",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(34, 34, 34))",
												}}
											>
												{
													"Booking your parcel delivery is easy, no matter where in the world you\u2019re shipping to! All you need to do is put your parcel\u2019s destination and measurements into our "
												}
												<Link
													href={"https://parcel2go.com/quick-quote"}
													motionChild={true}
													nodeId={"xJlVvLoZr"}
													openInNewTab={false}
													relValues={[]}
													scopeId={"eV8ELUnGI"}
													smoothScroll={false}
												>
													<motion2.a>
														<motion2.span
															style={{
																"--font-selector":
																	"R0Y7UGx1cyBKYWthcnRhIFNhbnMtNzAw",
																"--framer-font-weight": "700",
																"--framer-text-color":
																	"var(--extracted-hl0iuy, rgb(12, 80, 239))",
																"--framer-text-decoration": "underline",
															}}
														>
															{"quick quote tool"}
														</motion2.span>
													</motion2.a>
												</Link>
												{
													". From there you can compare parcel prices from the most reliable "
												}
												<Link
													href={"https://parcel2go.com/international-couriers"}
													motionChild={true}
													nodeId={"xJlVvLoZr"}
													openInNewTab={false}
													relValues={[]}
													scopeId={"eV8ELUnGI"}
													smoothScroll={false}
												>
													<motion2.a>
														<motion2.span
															style={{
																"--font-selector":
																	"R0Y7UGx1cyBKYWthcnRhIFNhbnMtNzAw",
																"--framer-font-weight": "700",
																"--framer-text-color":
																	"var(--extracted-zp3slp, rgb(12, 80, 239))",
																"--framer-text-decoration": "underline",
															}}
														>
															{"international couriers"}
														</motion2.span>
													</motion2.a>
												</Link>
												{"."}
											</motion2.p>
											<motion2.p
												style={{
													"--font-selector":
														"R0Y7UGx1cyBKYWthcnRhIFNhbnMtcmVndWxhcg==",
													"--framer-font-family":
														'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
													"--framer-line-height": "22px",
													"--framer-text-color":
														"var(--extracted-2gxw0f, rgb(34, 34, 34))",
												}}
											>
												<motion2.br className={"trailing-break"} />
											</motion2.p>
											<motion2.p
												style={{
													"--font-selector":
														"R0Y7UGx1cyBKYWthcnRhIFNhbnMtcmVndWxhcg==",
													"--framer-font-family":
														'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
													"--framer-line-height": "22px",
													"--framer-text-color":
														"var(--extracted-1iakedh, rgb(34, 34, 34))",
												}}
											>
												{"Whether you need to send a parcel to "}
												<Link
													href={
														"https://parcel2go.com/parcel-delivery/australia"
													}
													motionChild={true}
													nodeId={"xJlVvLoZr"}
													openInNewTab={false}
													relValues={[]}
													scopeId={"eV8ELUnGI"}
													smoothScroll={false}
												>
													<motion2.a>
														<motion2.span
															style={{
																"--font-selector":
																	"R0Y7UGx1cyBKYWthcnRhIFNhbnMtNzAw",
																"--framer-font-weight": "700",
																"--framer-text-color":
																	"var(--extracted-e385wm, rgb(12, 80, 239))",
																"--framer-text-decoration": "underline",
															}}
														>
															{"Australia"}
														</motion2.span>
													</motion2.a>
												</Link>
												{", the "}
												<Link
													href={"https://parcel2go.com/parcel-delivery/usa"}
													motionChild={true}
													nodeId={"xJlVvLoZr"}
													openInNewTab={false}
													relValues={[]}
													scopeId={"eV8ELUnGI"}
													smoothScroll={false}
												>
													<motion2.a>
														<motion2.span
															style={{
																"--font-selector":
																	"R0Y7UGx1cyBKYWthcnRhIFNhbnMtNzAw",
																"--framer-font-weight": "700",
																"--framer-text-color":
																	"var(--extracted-o257m, rgb(12, 80, 239))",
																"--framer-text-decoration": "underline",
															}}
														>
															{"USA"}
														</motion2.span>
													</motion2.a>
												</Link>
												{
													" or beyond, we will send you all the documents you need to clear customs."
												}
											</motion2.p>
											<motion2.p
												style={{
													"--font-selector":
														"R0Y7UGx1cyBKYWthcnRhIFNhbnMtcmVndWxhcg==",
													"--framer-font-family":
														'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
													"--framer-line-height": "22px",
													"--framer-text-color":
														"var(--extracted-14qxiz, rgb(34, 34, 34))",
												}}
											>
												{"Our "}
												<Link
													href={
														"https://parcel2go.com/international-shipping-hub"
													}
													motionChild={true}
													nodeId={"xJlVvLoZr"}
													openInNewTab={false}
													relValues={[]}
													scopeId={"eV8ELUnGI"}
													smoothScroll={false}
												>
													<motion2.a>
														<motion2.span
															style={{
																"--font-selector":
																	"R0Y7UGx1cyBKYWthcnRhIFNhbnMtNzAw",
																"--framer-font-weight": "700",
																"--framer-text-color":
																	"var(--extracted-1o3d6wc, rgb(12, 80, 239))",
																"--framer-text-decoration": "underline",
															}}
														>
															{"International Shipping Hub"}
														</motion2.span>
													</motion2.a>
												</Link>
												{
													" is full of helpful information for sending a parcel to the EU, with details on EU VAT, shipping restrictions and more."
												}
											</motion2.p>
										</React2.Fragment>
									</RichText>
								</motion2.div>
							</motion2.div>
							<motion2.div
								className={"framer-19u0gp3"}
								data-framer-name={"Desktop / Main Button 2"}
								layoutDependency={layoutDependency}
								layoutId={"OvSgiURiz"}
								style={{
									backgroundColor: "rgb(12, 80, 239)",
									borderBottomLeftRadius: 10,
									borderBottomRightRadius: 10,
									borderTopLeftRadius: 10,
									borderTopRightRadius: 10,
								}}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-9gjclg"}
									data-framer-name={"Label"}
									fonts={["GF;Plus Jakarta Sans-700"]}
									layoutDependency={layoutDependency}
									layoutId={"I722:21017;575:6096"}
									style={{
										"--extracted-r6o4lv": "rgb(255, 255, 255)",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											style={{
												"--font-selector": "R0Y7UGx1cyBKYWthcnRhIFNhbnMtNzAw",
												"--framer-font-family":
													'"Plus Jakarta Sans", "Plus Jakarta Sans Placeholder", sans-serif',
												"--framer-font-size": "20px",
												"--framer-font-weight": "700",
												"--framer-line-height": "25px",
												"--framer-text-alignment": "center",
												"--framer-text-color":
													"var(--extracted-r6o4lv, rgb(255, 255, 255))",
											}}
										>
											{"Get a Quote"}
										</motion2.p>
									</React2.Fragment>
								</RichText>
							</motion2.div>
						</motion2.div>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-KD6PO.framer-16f52sm, .framer-KD6PO .framer-16f52sm { display: block; }",
	".framer-KD6PO.framer-192b1nv { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 48px; height: 800px; justify-content: flex-start; overflow: visible; padding: 48px; position: relative; width: 1721px; }",
	".framer-KD6PO .framer-f7epi1 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: flex-end; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-KD6PO .framer-859o9q { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: 100%; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 462px; }",
	".framer-KD6PO .framer-1mhiz1s { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 1px; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-KD6PO .framer-inne47 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: 100%; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-KD6PO .framer-1tsoghh { flex: 1 0 0px; height: 1px; overflow: visible; position: relative; width: 451px; }",
	".framer-KD6PO .framer-jfmmrh, .framer-KD6PO .framer-14fw8rm { flex: none; height: 100%; left: 0px; position: absolute; right: 0px; top: 0px; }",
	".framer-KD6PO .framer-1hm0afd { flex: none; height: auto; left: 0px; position: absolute; right: 0px; top: 0px; }",
	".framer-KD6PO .framer-15v8qpq { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-KD6PO .framer-v7rmry, .framer-KD6PO .framer-1tww205, .framer-KD6PO .framer-vq0kjb { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 12px 32px 12px 32px; position: relative; width: min-content; }",
	".framer-KD6PO .framer-117oakt, .framer-KD6PO .framer-1ful7dt, .framer-KD6PO .framer-13ti3p, .framer-KD6PO .framer-9gjclg { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-KD6PO .framer-3mkl4x-container { flex: none; height: 15px; position: relative; width: 66px; }",
	".framer-KD6PO .framer-p3g15a { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 48px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-KD6PO .framer-uh5634 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 48px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-KD6PO .framer-m9qwcx { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 789px; word-break: break-word; word-wrap: break-word; }",
	".framer-KD6PO .framer-oak47s { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-KD6PO .framer-12ojwdu { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-KD6PO .framer-19u0gp3 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 44px; justify-content: center; overflow: visible; padding: 8px 32px 8px 32px; position: relative; width: 215px; }",
	'.framer-KD6PO[data-border="true"]::after, .framer-KD6PO [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramereV8ELUnGI = withCSS2(Component2, css2, "framer-KD6PO");
var stdin_default2 = FramereV8ELUnGI;
FramereV8ELUnGI.displayName = "desktop component";
FramereV8ELUnGI.defaultProps = {
	height: 800,
	width: 1721,
};
addPropertyControls2(FramereV8ELUnGI, {
	variant: {
		options: ["l9UZ5xyJt", "Xhfv0P_Uf", "Oy1CEl_9C"],
		optionTitles: ["Variant 1", "Variant 2", "Variant 3"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts2(
	FramereV8ELUnGI,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Plus Jakarta Sans",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/plusjakartasans/v12/LDIbaomQNQcsA88c7O9yZ4KMCoOg4IA6-91aHEjcWuA_TknNTxXUEKi4Rw.woff2",
					weight: "700",
				},
				{
					family: "Plus Jakarta Sans",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/plusjakartasans/v12/LDIbaomQNQcsA88c7O9yZ4KMCoOg4IA6-91aHEjcWuA_KUnNTxXUEKi4Rw.woff2",
					weight: "800",
				},
				{
					family: "Plus Jakarta Sans",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/plusjakartasans/v12/LDIbaomQNQcsA88c7O9yZ4KMCoOg4IA6-91aHEjcWuA_qU7NTxXUEKi4Rw.woff2",
					weight: "400",
				},
			],
		},
		...LoaderFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:desktop-component
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "l9UZ5xyJt",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"694ba3e94fb76b4ce494af0321e2878aece3f266b6b7ecbacf7c9a265ee933bc"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders DesktopComponentFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"694ba3e94fb76b4ce494af0321e2878aece3f266b6b7ecbacf7c9a265ee933bc"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var desktop_component_default = ComponentWithRoot;
export { desktop_component_default as default };
