// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 694ba3e94fb76b4c "test", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' // Variant
}} Props

 */
import { routes } from "./chunks/chunk-VAWW4KIH.js";

// virtual:loader
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/loader-fkIF.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFX = withFX(motion.div);
var cycleOrder = ["QC7nUFQy_", "RQnWSzAa2"];
var serializationHash = "framer-zAtlt";
var variantClassNames = {
	QC7nUFQy_: "framer-v-1uyk5dt",
	RQnWSzAa2: "framer-v-hikaev",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 4,
	type: "spring",
};
var transition2 = {
	delay: 0,
	duration: 4,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 51,
	y: 0,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "QC7nUFQy_",
	"Variant 2": "RQnWSzAa2",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "QC7nUFQy_",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "QC7nUFQy_",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppearn922d6 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("RQnWSzAa2", true), 4e3);
	});
	useOnVariantChange(baseVariant, {
		default: onAppearn922d6,
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1uyk5dt",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"QC7nUFQy_"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								RQnWSzAa2: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-jnzzxt"}
							data-border={true}
							data-framer-name={"Rectangle 1625"}
							layoutDependency={layoutDependency}
							layoutId={"I722:21065;717:20483"}
							style={{
								"--border-bottom-width": "2px",
								"--border-color": "rgb(8, 28, 70)",
								"--border-left-width": "2px",
								"--border-right-width": "2px",
								"--border-style": "solid",
								"--border-top-width": "2px",
								borderBottomLeftRadius: 12.5,
								borderBottomRightRadius: 12.5,
								borderTopLeftRadius: 12.5,
								borderTopRightRadius: 12.5,
							}}
						/>
						<MotionDivWithFX
							__framer__loop={animation}
							__framer__loopEffectEnabled={true}
							__framer__loopPauseOffscreen={true}
							__framer__loopRepeatDelay={0}
							__framer__loopRepeatType={"loop"}
							__framer__loopTransition={transition2}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							className={"framer-7meel4"}
							data-framer-name={"Rectangle 1626"}
							layoutDependency={layoutDependency}
							layoutId={"I722:21065;717:20484"}
							style={{
								backgroundColor: "rgb(8, 28, 70)",
								borderBottomLeftRadius: 12.5,
								borderBottomRightRadius: 12.5,
								borderTopLeftRadius: 12.5,
								borderTopRightRadius: 12.5,
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-zAtlt.framer-1tgtaqi, .framer-zAtlt .framer-1tgtaqi { display: block; }",
	".framer-zAtlt.framer-1uyk5dt { gap: 0px; height: 15px; overflow: visible; position: relative; width: 66px; }",
	".framer-zAtlt .framer-jnzzxt { flex: none; height: 15px; left: 0px; position: absolute; top: 0px; width: 66px; }",
	".framer-zAtlt .framer-7meel4 { flex: none; height: 15px; left: 0px; position: absolute; top: 0px; width: 15px; }",
	'.framer-zAtlt[data-border="true"]::after, .framer-zAtlt [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var Framergb4SAU21p = withCSS(Component, css, "framer-zAtlt");
var stdin_default = Framergb4SAU21p;
Framergb4SAU21p.displayName = "loader";
Framergb4SAU21p.defaultProps = {
	height: 15,
	width: 66,
};
addPropertyControls(Framergb4SAU21p, {
	variant: {
		options: ["QC7nUFQy_", "RQnWSzAa2"],
		optionTitles: ["Variant 1", "Variant 2"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	Framergb4SAU21p,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:loader
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "QC7nUFQy_",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"694ba3e94fb76b4ce494af0321e2878aece3f266b6b7ecbacf7c9a265ee933bc"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders LoaderFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"694ba3e94fb76b4ce494af0321e2878aece3f266b6b7ecbacf7c9a265ee933bc"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var loader_default = ComponentWithRoot;
export { loader_default as default };
